package com.diane.blog.model;

import org.springframework.stereotype.Component;

import java.io.Serializable;
import java.util.Date;

@Component
public class TblArticleCategory implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_article_category.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_article_category.sort_id
     *
     * @mbggenerated
     */
    private Integer sortId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_article_category.article_id
     *
     * @mbggenerated
     */
    private String articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_article_category.create_by
     *
     * @mbggenerated
     */
    private Date createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_article_category.modified_by
     *
     * @mbggenerated
     */
    private Date modifiedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_article_category.is_effective
     *
     * @mbggenerated
     */
    private Boolean isEffective;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_article_category.id
     *
     * @return the value of tbl_article_category.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_article_category.id
     *
     * @param id the value for tbl_article_category.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_article_category.sort_id
     *
     * @return the value of tbl_article_category.sort_id
     *
     * @mbggenerated
     */
    public Integer getSortId() {
        return sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_article_category.sort_id
     *
     * @param sortId the value for tbl_article_category.sort_id
     *
     * @mbggenerated
     */
    public void setSortId(Integer sortId) {
        this.sortId = sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_article_category.article_id
     *
     * @return the value of tbl_article_category.article_id
     *
     * @mbggenerated
     */
    public String getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_article_category.article_id
     *
     * @param articleId the value for tbl_article_category.article_id
     *
     * @mbggenerated
     */
    public void setArticleId(String articleId) {
        this.articleId = articleId == null ? null : articleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_article_category.create_by
     *
     * @return the value of tbl_article_category.create_by
     *
     * @mbggenerated
     */
    public Date getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_article_category.create_by
     *
     * @param createBy the value for tbl_article_category.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(Date createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_article_category.modified_by
     *
     * @return the value of tbl_article_category.modified_by
     *
     * @mbggenerated
     */
    public Date getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_article_category.modified_by
     *
     * @param modifiedBy the value for tbl_article_category.modified_by
     *
     * @mbggenerated
     */
    public void setModifiedBy(Date modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_article_category.is_effective
     *
     * @return the value of tbl_article_category.is_effective
     *
     * @mbggenerated
     */
    public Boolean getIsEffective() {
        return isEffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_article_category.is_effective
     *
     * @param isEffective the value for tbl_article_category.is_effective
     *
     * @mbggenerated
     */
    public void setIsEffective(Boolean isEffective) {
        this.isEffective = isEffective;
    }
}