package com.diane.blog.model;

import org.springframework.stereotype.Component;

import java.util.Date;
@Component
public class TblArticleInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_article_info.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_article_info.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_article_info.summary
     *
     * @mbggenerated
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_article_info.is_top
     *
     * @mbggenerated
     */
    private Boolean isTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_article_info.traffic
     *
     * @mbggenerated
     */
    private Integer traffic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_article_info.create_by
     *
     * @mbggenerated
     */
    private Date createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_article_info.modified_by
     *
     * @mbggenerated
     */
    private Date modifiedBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_article_info.id
     *
     * @return the value of tbl_article_info.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_article_info.id
     *
     * @param id the value for tbl_article_info.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_article_info.title
     *
     * @return the value of tbl_article_info.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_article_info.title
     *
     * @param title the value for tbl_article_info.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_article_info.summary
     *
     * @return the value of tbl_article_info.summary
     *
     * @mbggenerated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_article_info.summary
     *
     * @param summary the value for tbl_article_info.summary
     *
     * @mbggenerated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_article_info.is_top
     *
     * @return the value of tbl_article_info.is_top
     *
     * @mbggenerated
     */
    public Boolean getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_article_info.is_top
     *
     * @param isTop the value for tbl_article_info.is_top
     *
     * @mbggenerated
     */
    public void setIsTop(Boolean isTop) {
        this.isTop = isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_article_info.traffic
     *
     * @return the value of tbl_article_info.traffic
     *
     * @mbggenerated
     */
    public Integer getTraffic() {
        return traffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_article_info.traffic
     *
     * @param traffic the value for tbl_article_info.traffic
     *
     * @mbggenerated
     */
    public void setTraffic(Integer traffic) {
        this.traffic = traffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_article_info.create_by
     *
     * @return the value of tbl_article_info.create_by
     *
     * @mbggenerated
     */
    public Date getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_article_info.create_by
     *
     * @param createBy the value for tbl_article_info.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(Date createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_article_info.modified_by
     *
     * @return the value of tbl_article_info.modified_by
     *
     * @mbggenerated
     */
    public Date getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_article_info.modified_by
     *
     * @param modifiedBy the value for tbl_article_info.modified_by
     *
     * @mbggenerated
     */
    public void setModifiedBy(Date modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
}