spring:
  datasource:
    url: jdbc:mysql://8.131.228.245:3306/blog?useUnicode=true&useSSL=false&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: dgy990416
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:/static/,classpath:/view/,classpath:/public,classpath:/resources,classpath:/META-INF/
  redis:
    host: 8.131.228.245
    password:
    jedis:
      pool:
        max-active: 8   #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1    #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8    #连接池中的最大空闲连接
        min-idle: 0   #连接池中的最小空闲连接
    timeout: 30000
server:
  port: 8081
  servlet:
    context-path: /

mybatis:
  configuration:
    cache-enabled: false #禁用二级缓存
    local-cache-scope: statement #一级缓存指定为statement级别
    map-underscore-to-camel-case: true #数据库表字段映射自动转驼峰
  mapper-locations: classpath:/mapper/*.xml

