spring:
  datasource:
    url: jdbc:mysql://8.131.228.245:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone =Asia/Shanghai
    username: root
    password: dgy990416
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:/static/,classpath:/view/,classpath:/public,classpath:/resources,classpath:/META-INF/

server:
  port: 8081
  servlet:
    context-path: /

mybatis:
  mapper-locations: classpath:/mapper/*.xml