package com.diane.blog.dao;

import com.diane.blog.model.TblArticleCategory;
import com.diane.blog.model.TblArticleCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Component;

@Component
public interface TblArticleCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_category
     *
     * @mbggenerated
     */
    int countByExample(TblArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_category
     *
     * @mbggenerated
     */
    int deleteByExample(TblArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_category
     *
     * @mbggenerated
     */
    int insert(TblArticleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_category
     *
     * @mbggenerated
     */
    int insertSelective(TblArticleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_category
     *
     * @mbggenerated
     */
    List<TblArticleCategory> selectByExample(TblArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_category
     *
     * @mbggenerated
     */
    TblArticleCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_category
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblArticleCategory record, @Param("example") TblArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_category
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblArticleCategory record, @Param("example") TblArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblArticleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblArticleCategory record);

    //    传入一个artId，使该文章所在目录下的文章数量-1
    @Select("UPDATE tbl_category_info SET number = number -1 WHERE id =(SELECT ac.sort_id FROM tbl_article_category ac WHERE ac.article_id = #{artId});")
    void reducecateinfonum(String artId);
}