package com.diane.blog.dao;

import com.diane.blog.model.TblArticlePicture;
import com.diane.blog.model.TblArticlePictureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblArticlePictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_picture
     *
     * @mbggenerated
     */
    int countByExample(TblArticlePictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_picture
     *
     * @mbggenerated
     */
    int deleteByExample(TblArticlePictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_picture
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_picture
     *
     * @mbggenerated
     */
    int insert(TblArticlePicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_picture
     *
     * @mbggenerated
     */
    int insertSelective(TblArticlePicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_picture
     *
     * @mbggenerated
     */
    List<TblArticlePicture> selectByExample(TblArticlePictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_picture
     *
     * @mbggenerated
     */
    TblArticlePicture selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_picture
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblArticlePicture record, @Param("example") TblArticlePictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_picture
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblArticlePicture record, @Param("example") TblArticlePictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_picture
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblArticlePicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_picture
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblArticlePicture record);
}