package com.diane.blog.dao;

import com.diane.blog.model.TblArticleCategory;
import com.diane.blog.model.TblArticleCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface TblArticleCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_category
     *
     * @mbggenerated
     */
    int countByExample(TblArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_category
     *
     * @mbggenerated
     */
    int deleteByExample(TblArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_category
     *
     * @mbggenerated
     */
    int insert(TblArticleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_category
     *
     * @mbggenerated
     */
    int insertSelective(TblArticleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_category
     *
     * @mbggenerated
     */
    List<TblArticleCategory> selectByExample(TblArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_category
     *
     * @mbggenerated
     */
    TblArticleCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_category
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblArticleCategory record, @Param("example") TblArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_category
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblArticleCategory record, @Param("example") TblArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblArticleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblArticleCategory record);
}