package com.diane.blog.dao;

import com.diane.blog.model.TblCategoryInfo;
import com.diane.blog.model.TblCategoryInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblCategoryInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_info
     *
     * @mbggenerated
     */
    int countByExample(TblCategoryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_info
     *
     * @mbggenerated
     */
    int deleteByExample(TblCategoryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_info
     *
     * @mbggenerated
     */
    int insert(TblCategoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_info
     *
     * @mbggenerated
     */
    int insertSelective(TblCategoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_info
     *
     * @mbggenerated
     */
    List<TblCategoryInfo> selectByExample(TblCategoryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_info
     *
     * @mbggenerated
     */
    TblCategoryInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblCategoryInfo record, @Param("example") TblCategoryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblCategoryInfo record, @Param("example") TblCategoryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblCategoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblCategoryInfo record);
}